#mcandrew

import sys
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

if __name__ == "__main__":

    truthDB = pd.DataFrame()
    
    truth = {'questionLabel':[],'truth':[]}

    # SURVEY1 (2020-02-17)
    truth['questionLabel'].append('Q0-1')
    truth['questionLabel'].append('QR-1-0')
    truth['questionLabel'].append('QR-2-0')
    truth['questionLabel'].append('QF-1-0')
    truth['questionLabel'].append('QF-1-1_1')
    truth['questionLabel'].append('QF-2-0')
    truth['questionLabel'].append('QF-2_1')
    truth['questionLabel'].append('QF-2_2_1')
    truth['questionLabel'].append('QF-2_2_2')
    truth['questionLabel'].append('QF-2_2_3')
    truth['questionLabel'].append('QF-3-0')

    #truth
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(1)
    truth['truth'].append(1)
    truth['truth'].append(1)
    truth['truth'].append(1)
    truth['truth'].append(35)
    truth['truth'].append(35)
    truth['truth'].append(35)
    truth['truth'].append(np.nan)

    truth = pd.DataFrame(truth)
    truth['surveyIssued'] = '2020-02-17'
    truthDB = truthDB.append(truth)

    # SURVEY2 (2020-02-24)
    truth = {'questionLabel':[],'truth':[]}
    
    truth['questionLabel'].append('Q0-1')
    truth['questionLabel'].append('QR-1-0')
    truth['questionLabel'].append('QR-2-0')
    truth['questionLabel'].append('QF1')
    truth['questionLabel'].append('QF2_1')
    truth['questionLabel'].append('QF3')
    truth['questionLabel'].append('QF4_1')
    truth['questionLabel'].append('QF5_1')
    truth['questionLabel'].append('QF5_2')
    truth['questionLabel'].append('QF5_3')
    truth['questionLabel'].append('QF6_1')
    truth['questionLabel'].append('QF6_2')
    truth['questionLabel'].append('QF6_3')
    truth['questionLabel'].append('QF7')

    #truth
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(1)
    truth['truth'].append(1)
    truth['truth'].append(1)
    truth['truth'].append(1)
    truth['truth'].append(62)
    truth['truth'].append(62)
    truth['truth'].append(62)
    truth['truth'].append(7)
    truth['truth'].append(7)
    truth['truth'].append(7)
    truth['truth'].append(np.nan)

    truth = pd.DataFrame(truth)
    truth['surveyIssued'] = '2020-02-24'
    truthDB = truthDB.append(truth)

    # SURVEY3 (2020-03-02)
    truth = {'questionLabel':[],'truth':[]}
    
    truth['questionLabel'].append('Q0-1')
    truth['questionLabel'].append('QR-1-0')
    truth['questionLabel'].append('QR-2-0')
    truth['questionLabel'].append('QF1_1')
    truth['questionLabel'].append('QF1_2')
    truth['questionLabel'].append('QF1_3')
    truth['questionLabel'].append('QF2_1')
    truth['questionLabel'].append('QF2_2')
    truth['questionLabel'].append('QF2_3')
    truth['questionLabel'].append('QF3_1')
    truth['questionLabel'].append('QF3_2')
    truth['questionLabel'].append('QF3_3')
    truth['questionLabel'].append('QF4_1')
    truth['questionLabel'].append('QF4_2')
    truth['questionLabel'].append('QF4_3')
    truth['questionLabel'].append('QF5_1')
    truth['questionLabel'].append('QF5_2')
    truth['questionLabel'].append('QF5_3')
    truth['questionLabel'].append('QF6_1')
    truth['questionLabel'].append('QF6_2')
    truth['questionLabel'].append('QF6_3')
    truth['questionLabel'].append('QF7')

    #truth
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(423)
    truth['truth'].append(423)
    truth['truth'].append(423)
    truth['truth'].append(3487)
    truth['truth'].append(3487)
    truth['truth'].append(3487)
    truth['truth'].append(35)
    truth['truth'].append(35)
    truth['truth'].append(35)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(17)
    truth['truth'].append(17)
    truth['truth'].append(17)
    truth['truth'].append(np.nan)

    truth = pd.DataFrame(truth)
    truth['surveyIssued'] = '2020-03-02'
    truthDB = truthDB.append(truth)

    # SURVEY4 (2020-03-09)
    truth = {'questionLabel':[],'truth':[]}
    
    truth['questionLabel'].append('Q0-1')
    truth['questionLabel'].append('QR-1-0')
    truth['questionLabel'].append('QR-2-0')
    truth['questionLabel'].append('QF1_1')
    truth['questionLabel'].append('QF1_2')
    truth['questionLabel'].append('QF1_3')
    truth['questionLabel'].append('QF2_1')
    truth['questionLabel'].append('QF2_2')
    truth['questionLabel'].append('QF2_3')
    truth['questionLabel'].append('QF3')
    truth['questionLabel'].append('QF4_1')
    truth['questionLabel'].append('QF4_2')
    truth['questionLabel'].append('QF4_3')
    truth['questionLabel'].append('QF6_1')
    truth['questionLabel'].append('QF6_2')
    truth['questionLabel'].append('QF6_3')
    truth['questionLabel'].append('QF7')
    truth['questionLabel'].append('QF8')
    truth['questionLabel'].append('QF9')

    #truth
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(3487)
    truth['truth'].append(3487)
    truth['truth'].append(3487)
    truth['truth'].append(49)
    truth['truth'].append(49)
    truth['truth'].append(49)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)

    truth = pd.DataFrame(truth)
    truth['surveyIssued'] = '2020-03-09'
    truthDB = truthDB.append(truth)

    # SURVEY5 (2020-03-16)
    truth = {'questionLabel':[],'truth':[]}

    truth['questionLabel'].append('Q0-1')
    truth['questionLabel'].append('QR-1-0')
    truth['questionLabel'].append('QR-2-0')
    truth['questionLabel'].append('QF1_1')
    truth['questionLabel'].append('QF1_2')
    truth['questionLabel'].append('QF1_3')
    truth['questionLabel'].append('QF2_1')
    truth['questionLabel'].append('QF2_2')
    truth['questionLabel'].append('QF2_3')
    truth['questionLabel'].append('QF3_1')
    truth['questionLabel'].append('QF3_2')
    truth['questionLabel'].append('QF3_3')
    truth['questionLabel'].append('QF4_1')
    truth['questionLabel'].append('QF4_2')
    truth['questionLabel'].append('QF4_3')
    truth['questionLabel'].append('QF5_1')
    truth['questionLabel'].append('QF5_2')
    truth['questionLabel'].append('QF5_3')
    truth['questionLabel'].append('QF6_1')
    truth['questionLabel'].append('QF7')
    truth['questionLabel'].append('QF8')

    #truth
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(33404)
    truth['truth'].append(33404)
    truth['truth'].append(33404)
    truth['truth'].append(139061)
    truth['truth'].append(139061)
    truth['truth'].append(139061)
    truth['truth'].append(32)
    truth['truth'].append(32)
    truth['truth'].append(32)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)

    truth = pd.DataFrame(truth)
    truth['surveyIssued'] = '2020-03-16'
    truthDB = truthDB.append(truth)
 
    
    # SURVEY6 (2020-03-23)
    truth = {'questionLabel':[],'truth':[]}
    
    truth['questionLabel'].append('Q0-1')
    truth['questionLabel'].append('QR-1-0')
    truth['questionLabel'].append('QR-2-0')
    truth['questionLabel'].append('QF1_1')
    truth['questionLabel'].append('QF1_2')
    truth['questionLabel'].append('QF1_3')
    truth['questionLabel'].append('QF2_1')
    truth['questionLabel'].append('QF2_2')
    truth['questionLabel'].append('QF2_3')
    truth['questionLabel'].append('QF3_1')
    truth['questionLabel'].append('QF3_2')
    truth['questionLabel'].append('QF3_3')
    truth['questionLabel'].append('QF4_1')
    truth['questionLabel'].append('QF4_2')
    truth['questionLabel'].append('QF4_3')
    truth['questionLabel'].append('QF5_1')
    truth['questionLabel'].append('QF5_2')
    truth['questionLabel'].append('QF5_3')
    truth['questionLabel'].append('QF6_1')
    truth['questionLabel'].append('QF6_4')
    truth['questionLabel'].append('QF6_5')
    truth['questionLabel'].append('QF6_6')
    truth['questionLabel'].append('QF6_7')
    truth['questionLabel'].append('QF6_8')
    truth['questionLabel'].append('QF7')
    truth['questionLabel'].append('QF8')

    #truth
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(139061)
    truth['truth'].append(139061)
    truth['truth'].append(139061)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(49)
    truth['truth'].append(49)
    truth['truth'].append(49)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    truth['truth'].append(np.nan)
    
    truth = pd.DataFrame(truth)
    truth['surveyIssued'] = '2020-03-23'
    truthDB = truthDB.append(truth)

    truthDB.to_csv('./database/truthDatabase.csv')
